# Generated by Django 5.2.7 on 2026-03-11 18:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=50)),
                ('slug', models.SlugField(unique=True)),
            ],
            options={
                'verbose_name_plural': 'Categorias',
            },
        ),
        migrations.CreateModel(
            name='Lead',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('servicos_selecionados', models.JSONField(default=list)),
                ('estimativa_complexidade', models.CharField(choices=[('BAIXA', 'Baixa'), ('MEDIA', 'Média'), ('ALTA', 'Alta')], max_length=10)),
                ('mensagem', models.TextField(blank=True)),
                ('data_criacao', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Projeto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('slug', models.SlugField(blank=True, unique=True)),
                ('descricao_curta', models.TextField()),
                ('thumbnail', models.ImageField(upload_to='portfolio/thumbnails/')),
                ('preview_video', models.FileField(blank=True, null=True, upload_to='portfolio/previews/')),
                ('tecnologias', models.CharField(max_length=200)),
                ('performance_metrics', models.JSONField(default=dict)),
                ('link_demo', models.URLField(blank=True)),
                ('link_repo', models.URLField(blank=True)),
                ('data_criacao', models.DateTimeField(auto_now_add=True)),
                ('categoria', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='projetos', to='core.categoria')),
            ],
        ),
    ]
