# Generated by Django 5.2.7 on 2026-03-11 20:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lead',
            name='estimativa_complexidade',
        ),
        migrations.RemoveField(
            model_name='lead',
            name='mensagem',
        ),
        migrations.RemoveField(
            model_name='lead',
            name='servicos_selecionados',
        ),
        migrations.AddField(
            model_name='lead',
            name='descricao_projeto',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='lead',
            name='whatsapp',
            field=models.CharField(default=1, max_length=20),
            preserve_default=False,
        ),
    ]
