# Generated by Django 5.2.7 on 2026-03-11 20:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_remove_lead_estimativa_complexidade_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='projeto',
            name='mostrar_live_view',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='projeto',
            name='mostrar_repo',
            field=models.BooleanField(default=True),
        ),
    ]
