# Generated by Django 5.2.7 on 2026-03-11 22:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_projeto_mostrar_live_view_projeto_mostrar_repo'),
    ]

    operations = [
        migrations.CreateModel(
            name='Certificado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=200)),
                ('slug', models.SlugField(blank=True, unique=True)),
                ('instituicao', models.CharField(max_length=200)),
                ('logotipo', models.ImageField(upload_to='certificados/logos/')),
                ('imagem_certificado', models.ImageField(upload_to='certificados/arquivos/')),
                ('descricao', models.TextField()),
                ('ordem', models.IntegerField(default=0)),
                ('data_conclusao', models.DateField(blank=True, null=True)),
                ('data_criacao', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['ordem', '-data_criacao'],
            },
        ),
    ]
