# Generated by Django 5.2.7 on 2026-03-13 13:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_certificado'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='projeto',
            name='preview_video',
        ),
        migrations.AddField(
            model_name='projeto',
            name='youtube_url',
            field=models.URLField(blank=True, help_text='Link do vídeo no YouTube', null=True),
        ),
    ]
